export const ROUTES = {
  ROOT: '/',
  START: '/start',
  HOME: '/home',
  SIGNIN: '/signin',
  SIGNUP: '/signup',
  FORGOTPASSWORD: '/forgot-password',
  RESETPASSWORD: '/reset-password',
  ONBOARDING: '/onboarding',
  ONBOARDING_V2: '/onboarding-v2',
  DASHBOARD: '/dashboard',
  SPENDING: '/spending',
  SPENDING_WALLET: '/spending/wallet',
  SPENDING_SCHEDULED: '/spending/scheduled',
  SPENDING_PERIODS: '/spending/periods',
  SPENDING_INSIGHTS: '/spending/insights',
  SPENDING_INSIGHTS_TAGS: '/spending/insights/tags',
  SPENDING_INSIGHTS_TAG_TRANSACTIONS: '/spending/insights/tags/:tagName',
  SPENDING_INSIGHTS_BUDGET: '/spending/insights/budget',
  SPENDING_CHECKINS: '/spending/checkins',
  SPENDING_CHECKINS_DETAIL: '/spending/checkins/:insightId',
  PROFILE: '/profile',
  SETTINGS: '/settings',
  SUBSCRIPTION_SUCCESS: '/subscription/success',
  SUBSCRIPTION_CANCEL: '/subscription/cancel',
  FEEDBACK: '/feedback',
  NOT_FOUND: '*',
} as const;
