export const ROUTES = {
  ROOT: '/',
  START: '/start',
  HOME: '/home',
  SIGNIN: '/signin',
  SIGNUP: '/signup',
  FORGOTPASSWORD: '/forgot-password',
  RESETPASSWORD: '/reset-password',
  ONBOARDING: '/onboarding',
  ONBOARDING_V2: '/onboarding-v2',
  DASHBOARD: '/dashboard',
  SPENDING: '/spending',
  SPENDING_WALLET: '/spending/wallet',
  SPENDING_SCHEDULED: '/spending/scheduled',
  SPENDING_PERIODS: '/spending/periods',
  PROFILE: '/profile',
  SETTINGS: '/settings',
  NOT_FOUND: '*',
} as const;
