export const MOOD_CONTEXTS: Record<string, string[]> = {
  happy: [
    'Celebrating a win',
    'Great news',
    'Treating the crew',
    'Feeling myself',
    'Sun is out',
    'Spontaneous adventure',
    'Finally off the clock',
    'Giving back',
    'Just because',
  ],
  stressed: [
    'Rough day at work',
    'Buried in emails',
    'Family drama',
    'Health scare',
    'Running late',
    'Financial pressure',
    'Endless to-do list',
    'Information overload',
    'Crowded environment',
  ],
  tired: [
    'Recharging social battery',
    'Late night/Early morning',
    'Physical burnout',
    'Deciding is too hard',
    'Can’t be bothered to cook',
    'Screen fatigue',
    'Post-travel exhaustion',
    'The 3PM slump',
  ],
  sad: [
    'Lonely night in',
    'Feeling misunderstood',
    'Missing home',
    'Bad breakup',
    'Grieving a loss',
    'Seasonal blues',
    'Disappointed by someone',
    'Filling a quiet house',
  ],
  angry: [
    'Argument with partner',
    'Traffic was a nightmare',
    'Felt disrespected',
    'Technical difficulties',
    'Unfair situation',
    'Venting frustrations',
    'Spite purchase',
  ],
  neutral: [
    'Just another Tuesday',
    'Grocery run',
    'Auto-pay/Subscription',
    'Sticking to the plan',
    'Replacing the basics',
    'Housekeeping',
    'Routine maintenance',
  ],
};
